src/main/resources/logback.xml

logback 설정 생성

---

src/main/java/databute/databuter/network/AbstractSession.java
src/main/java/databute/databuter/network/AbstractSessionAcceptor.java
src/main/java/databute/databuter/network/AbstractSessionConnector.java
src/main/java/databute/databuter/network/Session.java
src/main/java/databute/databuter/network/SessionAcceptor.java
src/main/java/databute/databuter/network/SessionConnector.java
src/main/java/databute/databuter/network/message/Message.java
src/main/java/databute/databuter/network/message/MessageCode.java
src/main/java/databute/databuter/network/message/MessageDeserializer.java
src/main/java/databute/databuter/network/message/MessageSerializer.java
src/main/java/databute/databuter/network/packet/AbstractPacket.java
src/main/java/databute/databuter/network/packet/BufferedPacket.java
src/main/java/databute/databuter/network/packet/Packet.java

네트워크 모듈 구현

---

config0.yaml
config1.yaml
config2.yaml
src/main/java/databute/databuter/cluster/Cluster.java
src/main/java/databute/databuter/cluster/ClusterConfiguration.java
src/main/java/databute/databuter/cluster/ClusterNode.java
src/main/java/databute/databuter/cluster/coordinator/ClusterCoordinator.java

ZooKeeper 기반 노드 디스커버리 구현

---

src/main/java/databute/databuter/cluster/Cluster.java

새로운 노드가 등록될 때 해당 노드와 연결

---

src/main/java/databute/databuter/cluster/network/ClusterMessageCode.java
src/main/java/databute/databuter/cluster/network/ClusterMessageCodeResolver.java
src/main/java/databute/databuter/cluster/network/ClusterSessionAcceptor.java
src/main/java/databute/databuter/cluster/network/ClusterSessionConnector.java
src/main/java/databute/databuter/network/message/MessageCodeResolver.java
src/main/java/databute/databuter/network/message/codec/MessageToPacketEncoder.java
src/main/java/databute/databuter/network/message/codec/PacketToMessageDecoder.java
src/main/java/databute/databuter/network/packet/BufferedPacket.java
src/main/java/databute/databuter/network/packet/codec/ByteToPacketDecoder.java
src/main/java/databute/databuter/network/packet/codec/PacketToByteEncoder.java

클러스터 간 통신 프로토콜 스택 구현

---

src/main/java/databute/databuter/cluster/handshake/request/HandshakeRequestMessageHandler.java
src/main/java/databute/databuter/cluster/network/OutboundClusterChannelHandler.java
src/main/java/databute/databuter/network/AbstractSession.java
src/main/java/databute/databuter/network/Session.java

 Session 클래스에 메시지 전송을 위한 메서드 추가

---

src/main/java/databute/databuter/cluster/handshake/request/HandshakeRequestMessageHandler.java
src/main/java/databute/databuter/network/AbstractSession.java
src/main/java/databute/databuter/network/Session.java

Session 클래스에 연결 해제를 위한 메서드 추가

---

src/main/java/databute/databuter/cluster/handshake/request/HandshakeRequestMessageHandler.java
src/main/java/databute/databuter/cluster/handshake/response/HandshakeResponseMessageHandler.java
src/main/java/databute/databuter/cluster/network/ClusterMessageHandler.java
src/main/java/databute/databuter/network/message/MessageHandler.java

메시지 핸들러가 channelRead0를 직접 override 하지 않도록 수정

---

src/main/java/databute/databuter/cluster/handshake/request/HandshakeRequestMessage.java
src/main/java/databute/databuter/cluster/handshake/response/HandshakeResponseMessage.java
src/main/java/databute/databuter/cluster/network/ClusterMessageCode.java
src/main/java/databute/databuter/cluster/network/ClusterSessionAcceptor.java
src/main/java/databute/databuter/cluster/network/ClusterSessionConnector.java

HANDSHAKE 메시지 코드 분리

---

src/main/java/databute/databuter/cluster/coordinator/RemoteClusterNodeGroup.java
src/main/java/databute/databuter/cluster/network/ClusterSession.java
src/main/java/databute/databuter/cluster/network/OutboundClusterChannelHandler.java

원격 노드와 연결이 끊어지면 원격 노드 그룹에서 해당 노드 제거

---

config.yaml
config0.yaml
config1.yaml
config2.yaml
src/main/java/databute/databuter/Databuter.java
src/main/java/databute/databuter/DatabuterConfiguration.java
src/main/java/databute/databuter/client/ClientConfiguration.java
src/main/java/databute/databuter/client/network/ClientChannelHandler.java
src/main/java/databute/databuter/client/network/ClientMessageCode.java
src/main/java/databute/databuter/client/network/ClientMessageCodeResolver.java
src/main/java/databute/databuter/client/network/ClientSession.java
src/main/java/databute/databuter/client/network/ClientSessionAcceptor.java

클라이언트와 통신하기 위한 서버 모듈을 구현함.
클라이언트와 통신하기 위한 프로토콜 코덱을 구현함.
close #40

클라이언트와 통신 구현

---

src/main/java/databute/databuter/Databuter.java
src/main/java/databute/databuter/bucket/Bucket.java
src/main/java/databute/databuter/bucket/BucketConfiguration.java
src/main/java/databute/databuter/bucket/BucketCoordinator.java
src/main/java/databute/databuter/cluster/ClusterCoordinator.java

최초 연결 시 zookeeper에서 Bucket에 관한 정보를 불러온 후, backupBucket이 없는 Bucket 에 대해서 backupBucket을 생성.
이 후, 남은 availableBucketCount가 있으면 그만큼 masterBucket을 생성하여 연결.
close #43

Bucket 역할 설정.

---

src/main/java/databute/databuter/Databuter.java
src/main/java/databute/databuter/client/network/ClientChannelHandler.java
src/main/java/databute/databuter/client/network/ClientMessageCode.java
src/main/java/databute/databuter/client/network/ClientMessageHandler.java
src/main/java/databute/databuter/client/network/ClientSession.java
src/main/java/databute/databuter/client/network/ClientSessionAcceptor.java
src/main/java/databute/databuter/client/network/ClientSessionGroup.java
src/main/java/databute/databuter/client/register/RegisterMessage.java
src/main/java/databute/databuter/client/register/RegisterMessageDeserializer.java
src/main/java/databute/databuter/client/register/RegisterMessageHandler.java

버킷 정보 모니터링을 등록한 클라이언트 유지

---

src/main/java/databute/databuter/bucket/Bucket.java
src/main/java/databute/databuter/bucket/BucketConfiguration.java
src/main/java/databute/databuter/bucket/BucketCoordinator.java
src/main/java/databute/databuter/bucket/BucketGroup.java

버킷 내에 configuration을 갖고 있도록 리팩토링.
버킷 수정을 통보 받았을 때 동기화.

ZooKeeper의 버킷 정보 모니터링

---

src/main/java/databute/databuter/client/cluster/add/AddClusterNodeMessage.java
src/main/java/databute/databuter/client/cluster/add/AddClusterNodeMessageSerializer.java
src/main/java/databute/databuter/client/cluster/remove/RemoveClusterNodeMessage.java
src/main/java/databute/databuter/client/cluster/remove/RemoveClusterNodeMessageSerializer.java
src/main/java/databute/databuter/client/network/ClientMessageCode.java
src/main/java/databute/databuter/client/network/ClientSessionAcceptor.java
src/main/java/databute/databuter/client/network/ClientSessionGroup.java
src/main/java/databute/databuter/client/register/RegisterMessageHandler.java
src/main/java/databute/databuter/cluster/AbstractClusterNode.java
src/main/java/databute/databuter/cluster/ClusterNode.java
src/main/java/databute/databuter/cluster/remote/RemoteClusterNodeGroup.java

클러스터가 변경될 때 마다 리스닝 클라이언트들에게 변경 정보 전송

---

src/main/java/databute/databuter/bucket/Bucket.java
src/main/java/databute/databuter/bucket/BucketConfiguration.java
src/main/java/databute/databuter/bucket/BucketCoordinator.java

버킷에 할당된 노드 식별자를 nodeId로 변경

---

src/main/java/databute/databuter/bucket/Bucket.java
src/main/java/databute/databuter/bucket/BucketConfiguration.java
src/main/java/databute/databuter/bucket/BucketCoordinator.java

버킷 타입을 액티브 버킷과 스탠바이 버킷으로 변경

---

src/main/java/databute/databuter/bucket/BucketConfiguration.java
src/main/java/databute/databuter/bucket/BucketCoordinator.java
src/main/java/databute/databuter/bucket/BucketGroup.java

버킷 생성 및 업데이트 로직 재작성

---

src/main/java/databute/databuter/bucket/BucketCoordinator.java
src/main/java/databute/databuter/bucket/BucketGroup.java
src/main/java/databute/databuter/bucket/local/LocalBucket.java

버킷 코디네이터 리팩토링

---

src/main/java/databute/databuter/bucket/BucketCoordinator.java
src/main/java/databute/databuter/bucket/SharedBucketFactor.java

Shared Bucket Factor 생성.

---

src/main/java/databute/databuter/bucket/BucketConfiguration.java
src/main/java/databute/databuter/bucket/BucketCoordinator.java

Bucket에 Factor 할당.

---

src/main/java/databute/databuter/bucket/Bucket.java
src/main/java/databute/databuter/bucket/BucketConfiguration.java
src/main/java/databute/databuter/bucket/BucketCoordinator.java
src/main/java/databute/databuter/bucket/BucketGroup.java
src/main/java/databute/databuter/bucket/SharedBucketFactor.java
src/main/java/databute/databuter/bucket/notification/BucketNotificationMessage.java
src/main/java/databute/databuter/bucket/notification/BucketNotificationMessageSerializer.java
src/main/java/databute/databuter/client/register/RegisterMessageHandler.java

버킷 변경 메시지에 factor 정보 추가

---

src/main/java/databute/databuter/client/network/ClientChannelHandler.java
src/main/java/databute/databuter/client/network/ClientSessionGroup.java

클라이언트 세션과 연결이 끊어지면 클라이언트 세션 그룹에서 해당 세션 제거

---

config.yaml
config0.yaml
config1.yaml
config2.yaml
src/main/java/databute/databuter/Databuter.java
src/main/java/databute/databuter/client/ClientConfiguration.java
src/main/java/databute/databuter/client/register/RegisterMessageHandler.java
src/main/java/databute/databuter/cluster/AbstractClusterNode.java
src/main/java/databute/databuter/cluster/ClusterConfiguration.java
src/main/java/databute/databuter/cluster/ClusterCoordinator.java
src/main/java/databute/databuter/cluster/ClusterNode.java
src/main/java/databute/databuter/cluster/ClusterNodeConfiguration.java
src/main/java/databute/databuter/cluster/notification/ClusterNodeNotificationMessage.java
src/main/java/databute/databuter/cluster/notification/ClusterNodeNotificationMessageSerializer.java
src/main/java/databute/databuter/cluster/remote/RemoteClusterNode.java
src/main/java/databute/databuter/cluster/remote/RemoteClusterNodeGroup.java
src/main/java/databute/databuter/network/Endpoint.java
src/main/java/databute/databuter/network/EndpointConfiguration.java

ZooKeeper에 저장하는 클러스터 노드 정보에 클라이언트용 정보 추가

---

src/main/java/databute/databuter/bucket/Bucket.java
src/main/java/databute/databuter/bucket/BucketGroup.java
src/main/java/databute/databuter/bucket/local/LocalBucket.java
src/main/java/databute/databuter/bucket/remote/RemoteBucket.java
src/main/java/databute/databuter/entity/delete/DeleteEntityMessageHandler.java
src/main/java/databute/databuter/entity/get/GetEntityMessageHandler.java
src/main/java/databute/databuter/entity/result/fail/EntityOperationErrorCode.java
src/main/java/databute/databuter/entity/result/fail/EntityOperationFailMessage.java
src/main/java/databute/databuter/entity/result/success/EntityOperationSuccessMessage.java
src/main/java/databute/databuter/entity/set/SetEntityMessageHandler.java
src/main/java/databute/databuter/entity/update/UpdateEntityMessageHandler.java
src/test/java/databute/databuter/entity/EntityKeyTest.java

로컬 버킷에 데이터 GET, SET, UPDATE, DELETE 구현

---

src/main/java/databute/databuter/Databuter.java
src/main/java/databute/databuter/bucket/local/LocalBucket.java
src/main/java/databute/databuter/client/network/ClientMessageHandler.java
src/main/java/databute/databuter/cluster/network/ClusterMessageHandler.java
src/main/java/databute/databuter/cluster/network/ClusterSessionAcceptor.java
src/main/java/databute/databuter/cluster/network/ClusterSessionConnector.java
src/main/java/databute/databuter/cluster/network/InboundClusterChannelHandler.java
src/main/java/databute/databuter/cluster/network/OutboundClusterChannelHandler.java
src/main/java/databute/databuter/entity/AbstractEntity.java
src/main/java/databute/databuter/entity/DuplicateEntityKeyException.java
src/main/java/databute/databuter/entity/EntityCallback.java
src/main/java/databute/databuter/entity/EntityMessageDispatcher.java
src/main/java/databute/databuter/entity/NotFoundException.java
src/main/java/databute/databuter/entity/delete/DeleteEntityMessageHandler.java
src/main/java/databute/databuter/entity/delete/DeleteEntityMessageSerializer.java
src/main/java/databute/databuter/entity/get/GetEntityMessageHandler.java
src/main/java/databute/databuter/entity/get/GetEntityMessageSerializer.java
src/main/java/databute/databuter/entity/result/fail/EntityOperationFailMessageDeserializer.java
src/main/java/databute/databuter/entity/result/fail/EntityOperationFailMessageHandler.java
src/main/java/databute/databuter/entity/result/success/EntityOperationSuccessMessage.java
src/main/java/databute/databuter/entity/result/success/EntityOperationSuccessMessageDeserializer.java
src/main/java/databute/databuter/entity/result/success/EntityOperationSuccessMessageHandler.java
src/main/java/databute/databuter/entity/set/SetEntityMessageHandler.java
src/main/java/databute/databuter/entity/set/SetEntityMessageSerializer.java
src/main/java/databute/databuter/entity/type/IntegerEntity.java
src/main/java/databute/databuter/entity/type/LongEntity.java
src/main/java/databute/databuter/entity/type/StringEntity.java
src/main/java/databute/databuter/entity/update/UpdateEntityMessageHandler.java
src/main/java/databute/databuter/entity/update/UpdateEntityMessageSerializer.java
src/main/java/databute/databuter/network/message/AbstractMessageHandler.java

클러스터 노드 간 데이터 프로토콜 구현

---

src/main/java/databute/databuter/bucket/Bucket.java
src/main/java/databute/databuter/bucket/local/LocalBucket.java
src/main/java/databute/databuter/bucket/remote/RemoteBucket.java
src/main/java/databute/databuter/entity/delete/DeleteEntityMessageHandler.java
src/main/java/databute/databuter/entity/get/GetEntityMessageHandler.java
src/main/java/databute/databuter/entity/set/SetEntityMessageHandler.java
src/main/java/databute/databuter/entity/update/UpdateEntityMessageHandler.java

버킷의 데이터 조작 연산을 콜백 방식으로 변경

---

src/main/java/databute/databuter/entity/EntityValueType.java
src/main/java/databute/databuter/entity/result/success/EntityOperationSuccessMessage.java
src/main/java/databute/databuter/entity/result/success/EntityOperationSuccessMessageDeserializer.java
src/main/java/databute/databuter/entity/result/success/EntityOperationSuccessMessageSerializer.java
src/main/java/databute/databuter/entity/set/SetEntityMessageDeserializer.java
src/main/java/databute/databuter/entity/set/SetEntityMessageHandler.java
src/main/java/databute/databuter/entity/set/SetEntityMessageSerializer.java
src/main/java/databute/databuter/entity/type/DictionaryEntity.java
src/main/java/databute/databuter/entity/type/ListEntity.java
src/main/java/databute/databuter/entity/type/SetEntity.java
src/main/java/databute/databuter/entity/update/UpdateEntityMessageDeserializer.java
src/main/java/databute/databuter/entity/update/UpdateEntityMessageHandler.java
src/main/java/databute/databuter/entity/update/UpdateEntityMessageSerializer.java

Collection 타입 엔티티 연산 구현

---

src/main/java/databute/databuter/bucket/BucketCoordinator.java

Bucket이 zookeeper에서 제거된 경우 BucketGroup에서 삭제.

---

src/main/java/databute/databuter/Databuter.java
src/main/java/databute/databuter/bucket/BucketCoordinator.java
src/main/java/databute/databuter/bucket/SharedKeyFactorCounter.java
src/main/java/databute/databuter/bucket/SharedKeyFactorException.java

액티브 버킷을 저장할 때, 버킷 전체에 락을 걸어줌.

---

src/main/java/databute/databuter/cluster/network/ClusterSession.java
src/main/java/databute/databuter/cluster/network/OutboundClusterChannelHandler.java

ActiveBucket이 삭제된 경우 StandbyBucket을 승격

---

src/main/java/databute/databuter/entry/result/success/EntryOperationSuccessMessageHandler.java

EntryOperationSuccessMessageHandler에 추가 안된 타입 추가.

---

src/main/java/databute/databuter/cluster/network/ClusterSessionAcceptor.java
src/main/java/databute/databuter/cluster/network/ClusterSessionConnector.java
src/main/java/databute/databuter/entry/delete/DeleteEntryMessageHandler.java
src/main/java/databute/databuter/entry/expire/ExpireEntryMessageHandler.java
src/main/java/databute/databuter/entry/result/success/EntryOperationSuccessMessageDeserializer.java
src/main/java/databute/databuter/entry/result/success/EntryOperationSuccessMessageSerializer.java
src/main/java/databute/databuter/entry/set/SetEntryMessageHandler.java
src/main/java/databute/databuter/entry/update/UpdateEntryMessageHandler.java

엔티티 연산 스탠바이 버킷에 연산 적용

---

src/main/java/databute/databuter/bucket/Bucket.java
src/main/java/databute/databuter/bucket/remote/RemoteBucket.java
src/main/java/databute/databuter/entry/delete/DeleteEntryMessage.java
src/main/java/databute/databuter/entry/expire/ExpireEntryMessage.java
src/main/java/databute/databuter/entry/get/GetEntryMessage.java
src/main/java/databute/databuter/entry/set/SetEntryMessage.java

RemoteBucket의 NotImplemented들 구현.
맞는 노드로 가서 연산을 수행한 후 결과를 받아와서 Databutee에게 전송하는 방식.

RemoteBucket의 NotImplemented들 구현.

---

.github/workflows/build.yml

push될 때 또는 pull request가 생성되었을 때 Gradle 빌드를 실행하는 GitHub Actions workflow를 추가한다.

GitHub Actions 빌드 workflow 추가
